[package]
name = "dsv-util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.18", features = ["derive"] }
csv = "1.1.6"
pest = "2.4.0"
pest_derive = "2.4.0"
regex = "1.6.0"
